-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler version: 1.0.0-beta1
-- PostgreSQL version: 15.0
-- Project Site: pgmodeler.io
-- Model Author: ---

-- Database creation must be performed outside a multi lined SQL file. 
-- These commands were put in this file only as a convenience.
-- 
-- object: bus_base | type: DATABASE --
-- DROP DATABASE IF EXISTS bus_base;
CREATE DATABASE bus_base;
-- ddl-end --


-- object: public.drivers | type: TABLE --
-- DROP TABLE IF EXISTS public.drivers CASCADE;
CREATE TABLE public.drivers (
	license_id int8 NOT NULL,
	last_name varchar(30) NOT NULL,
	first_name varchar(30) NOT NULL,
	patronymic varchar(30),
	date_of_birth date NOT NULL,
	work_hours numeric(9,4) NOT NULL DEFAULT 0,
	CONSTRAINT drivers_pk PRIMARY KEY (license_id),
	CONSTRAINT license_id_check CHECK (license_id <=9999999999 AND license_id >=100000000),
	CONSTRAINT birth_date_check CHECK (EXTRACT(YEAR FROM age(date_of_birth)) >= 18),
	CONSTRAINT work_h_check CHECK (work_hours>=0)
);
-- ddl-end --
ALTER TABLE public.drivers OWNER TO postgres;
-- ddl-end --

-- object: public.stops | type: TABLE --
-- DROP TABLE IF EXISTS public.stops CASCADE;
CREATE TABLE public.stops (
	stop_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	stop_name varchar(50) NOT NULL,
	latitude numeric(9,6) NOT NULL,
	longitude numeric(9,6) NOT NULL,
	dir bool,
	CONSTRAINT stops_pk PRIMARY KEY (stop_id),
	CONSTRAINT coords_uniq UNIQUE (latitude,longitude),
	CONSTRAINT stop_name_check CHECK (stop_name ~ '^[\dА-Я][-\d №".ёА-Яа-я]+$'),
	CONSTRAINT lat_check CHECK (latitude >=55.312602 AND latitude <= 56.406435),
	CONSTRAINT lon_check CHECK (longitude >=36.531199 AND longitude <= 38.371812)
);
-- ddl-end --
ALTER TABLE public.stops OWNER TO postgres;
-- ddl-end --

-- object: public.trips_stops | type: TABLE --
-- DROP TABLE IF EXISTS public.trips_stops CASCADE;
CREATE TABLE public.trips_stops (
	trip_stop_id int4 NOT NULL GENERATED ALWAYS AS IDENTITY ,
	trip_id int4 NOT NULL,
	stop_id int4 NOT NULL,
	stop_order int2,
	CONSTRAINT stop_ord_check CHECK (stop_order > 0),
	CONSTRAINT trips_stops_pk PRIMARY KEY (trip_stop_id),
	CONSTRAINT trip_stop_uq UNIQUE (trip_id,stop_id)
);
-- ddl-end --
ALTER TABLE public.trips_stops OWNER TO postgres;
-- ddl-end --

-- object: public.trips | type: TABLE --
-- DROP TABLE IF EXISTS public.trips CASCADE;
CREATE TABLE public.trips (
	trip_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	route_num varchar(6) NOT NULL,
	forward bool NOT NULL,
	CONSTRAINT trips_pk PRIMARY KEY (trip_id)
);
-- ddl-end --
ALTER TABLE public.trips OWNER TO postgres;
-- ddl-end --

-- object: public.routes | type: TABLE --
-- DROP TABLE IF EXISTS public.routes CASCADE;
CREATE TABLE public.routes (
	route_num varchar(6) NOT NULL,
	terminal_stop1 int4,
	terminal_stop2 int4,
	CONSTRAINT routes_pk PRIMARY KEY (route_num),
	CONSTRAINT route_num_check CHECK (route_num ~ '^[-\dа-яА-Я]+$')
);
-- ddl-end --
ALTER TABLE public.routes OWNER TO postgres;
-- ddl-end --

-- object: public.buses | type: TABLE --
-- DROP TABLE IF EXISTS public.buses CASCADE;
CREATE TABLE public.buses (
	bus_id varchar(9) NOT NULL,
	route_num varchar(7),
	model varchar(40),
	capacity int2,
	CONSTRAINT buses_pk PRIMARY KEY (bus_id),
	CONSTRAINT bus_id_check CHECK (bus_id ~ '^[АВЕКМНОРСТУХ]\d{3}(?<!000)[АВЕКМНОРСТУХ]{2}\d{2,3}$' OR
bus_id ~ '^[АВЕКМНОРСТУХ]{2}\d{3}(?<!000)\d{2,3}$'),
	CONSTRAINT capacity_check CHECK (capacity > 0)
);
-- ddl-end --
ALTER TABLE public.buses OWNER TO postgres;
-- ddl-end --

-- object: public.trips_departures | type: TABLE --
-- DROP TABLE IF EXISTS public.trips_departures CASCADE;
CREATE TABLE public.trips_departures (
	trip_id int4 NOT NULL,
	departure_time time NOT NULL,
	license_id int8,
	weekend bool NOT NULL,
	CONSTRAINT trips_departures_pk PRIMARY KEY (trip_id,departure_time,weekend)
);
-- ddl-end --
ALTER TABLE public.trips_departures OWNER TO postgres;
-- ddl-end --

-- object: public.stops_arrivals | type: TABLE --
-- DROP TABLE IF EXISTS public.stops_arrivals CASCADE;
CREATE TABLE public.stops_arrivals (
	trip_stop_id int4 NOT NULL,
	arrival_time time NOT NULL,
	CONSTRAINT stops_arrivals_pk PRIMARY KEY (arrival_time,trip_stop_id)
);
-- ddl-end --
ALTER TABLE public.stops_arrivals OWNER TO postgres;
-- ddl-end --

-- object: stop_id_fk | type: CONSTRAINT --
-- ALTER TABLE public.trips_stops DROP CONSTRAINT IF EXISTS stop_id_fk CASCADE;
ALTER TABLE public.trips_stops ADD CONSTRAINT stop_id_fk FOREIGN KEY (stop_id)
REFERENCES public.stops (stop_id) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: trip_id_fk | type: CONSTRAINT --
-- ALTER TABLE public.trips_stops DROP CONSTRAINT IF EXISTS trip_id_fk CASCADE;
ALTER TABLE public.trips_stops ADD CONSTRAINT trip_id_fk FOREIGN KEY (trip_id)
REFERENCES public.trips (trip_id) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: route_num_fk | type: CONSTRAINT --
-- ALTER TABLE public.trips DROP CONSTRAINT IF EXISTS route_num_fk CASCADE;
ALTER TABLE public.trips ADD CONSTRAINT route_num_fk FOREIGN KEY (route_num)
REFERENCES public.routes (route_num) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: term_stop1_fk | type: CONSTRAINT --
-- ALTER TABLE public.routes DROP CONSTRAINT IF EXISTS term_stop1_fk CASCADE;
ALTER TABLE public.routes ADD CONSTRAINT term_stop1_fk FOREIGN KEY (terminal_stop1)
REFERENCES public.stops (stop_id) MATCH SIMPLE
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: term_stop2_fk | type: CONSTRAINT --
-- ALTER TABLE public.routes DROP CONSTRAINT IF EXISTS term_stop2_fk CASCADE;
ALTER TABLE public.routes ADD CONSTRAINT term_stop2_fk FOREIGN KEY (terminal_stop2)
REFERENCES public.stops (stop_id) MATCH SIMPLE
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: route_num_fk | type: CONSTRAINT --
-- ALTER TABLE public.buses DROP CONSTRAINT IF EXISTS route_num_fk CASCADE;
ALTER TABLE public.buses ADD CONSTRAINT route_num_fk FOREIGN KEY (route_num)
REFERENCES public.routes (route_num) MATCH SIMPLE
ON DELETE SET NULL ON UPDATE NO ACTION;
-- ddl-end --

-- object: trip_id_fk | type: CONSTRAINT --
-- ALTER TABLE public.trips_departures DROP CONSTRAINT IF EXISTS trip_id_fk CASCADE;
ALTER TABLE public.trips_departures ADD CONSTRAINT trip_id_fk FOREIGN KEY (trip_id)
REFERENCES public.trips (trip_id) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: license_id_fk | type: CONSTRAINT --
-- ALTER TABLE public.trips_departures DROP CONSTRAINT IF EXISTS license_id_fk CASCADE;
ALTER TABLE public.trips_departures ADD CONSTRAINT license_id_fk FOREIGN KEY (license_id)
REFERENCES public.drivers (license_id) MATCH SIMPLE
ON DELETE SET NULL ON UPDATE NO ACTION;
-- ddl-end --

-- object: trip_stop_id_fk | type: CONSTRAINT --
-- ALTER TABLE public.stops_arrivals DROP CONSTRAINT IF EXISTS trip_stop_id_fk CASCADE;
ALTER TABLE public.stops_arrivals ADD CONSTRAINT trip_stop_id_fk FOREIGN KEY (trip_stop_id)
REFERENCES public.trips_stops (trip_stop_id) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --


